[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lop = "AF5GGw5ZMNLS3jWG14TgPGusj9USiiGu4hV8EXLbgGPd"
nyx_dispute = "EmnQbU9cHP5WWX8Q1LufdgLC7Z8vuQbZyivoK9cWo7BA"
nyx_oracle_bridge = "2nAAAhYY68Et9zoDv78GBB5zQMEawzCTZvNTg56JRkti"
nyx_settlement = "5givnWMR71eqWPEFDfh1mdBuhZUCSpnj3MuHUuKhzoYb"
nyx_verifier = "4tX5SEqVYiE35X6WAa8wxGTqiGvNgH9xdZJMk2Zes8Vz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
